### PR TITLE
attempt_guess: handle wordle guesses

### PR DESCRIPTION
**Pull request by 2003LK**
Takes in a string input and compares to the game word. Increments turn, generates feedback and list of guesses.

### CODE REVIEW

**Review by Gloria-Geng — COMMENTED** [review]
lines 85, 87, 89: you have to use the enum class for some reason otherwise the colors don't work. I figured that out while testing my print function.

**Comment by 2003LK** [comment]
Is this change enough @Gloria-Geng ?

**Comment by jasozh** [comment]
Is there a reason why we're using `numpy` instead of regular Python lists? I don't think performance is a concern since both `guesses` and `feedback` are just 5 x 6 arrays.

**Comment by 2003LK** [comment]
There was something I did that seemed to only be done using numpy, as in I legit didn’t find a function to do it without numpy.Sent from my iPhoneOn Mar 9, 2024, at 2:27 PM, jasozh ***@***.***> wrote:﻿
Is there a reason why we're using numpy instead of regular Python lists? I don't think performance is a concern since both guesses and feedback are just 5 x 6 arrays.

**Review by jasozh — CHANGES_REQUESTED** [review]
I'm testing out the function and I think `self.feedback` is malformed, see the output below:
```
word: hello
guesses: [['' '' '' '' '']
 ['p' 'h' 'o' 'n' 'e']
 ['s' 't' 'o' 'n' 'e']
 ['a' 's' 'd' 'f' 'g']
 ['s' 'd' 'f' 'g' 'h']
 ['z' 'x' 'c' 'v' 'b']
 ['h' 'e' 'l' 'l' 'o']]
feedback: [['101862562497934' '0' '0' '6864414021789941761' '28710745325261891']
 ['F' 'F' 'F' 'F' 'F']
 ['F' 'F' 'F' 'F' 'F']
 ['F' 'F' 'F' 'F' 'F']
 ['F' 'F' 'F' 'F' 'F']
 ['F' 'F' 'F' 'F' 'F']
 ['F' 'F' 'F' 'F' 'F']]
turn: 6
win: True
```

I think we should also stick with regular Python lists instead of numpy. What was the function you needed numpy for that you couldn't find in regular Python?

**Comment by 2003LK** [comment]
I believe just stacking the array, from what I saw there was using the + operator that would append elements, but didn't find anything besides numpy vstack for what I wanted

**Comment by 2003LK** [comment]
Fixed the enum problem, has colors now!

**Review by Gloria-Geng — APPROVED** [review]

**Review by jasozh — CHANGES_REQUESTED** [review]
Great work! I'm still getting some random numbers in `self.feedback` but not really sure why that's happening, and the first row of `self.guesses` is still empty:
```
>>> game.attempt_guess("hello")
>>> game
word: trait
guesses: [['' '' '' '' '']
 ['s' 't' 'a' 'i' 'r']
 ['b' 'l' 'a' 'i' 'r']
 ['h' 'e' 'l' 'l' 'o']]
feedback: [[106016178068355 0 0 6864414021789941761 297700774979]
 [<Feedback.GRAY: 0> <Feedback.YELLOW: 1> <Feedback.GREEN: 2>
  <Feedback.GREEN: 2> <Feedback.YELLOW: 1>]
 [<Feedback.GRAY: 0> <Feedback.GRAY: 0> <Feedback.GREEN: 2>
  <Feedback.GREEN: 2> <Feedback.YELLOW: 1>]
 [<Feedback.GRAY: 0> <Feedback.GRAY: 0> <Feedback.GRAY: 0>
  <Feedback.GRAY: 0> <Feedback.GRAY: 0>]]
turn: 3
win: False
>>> 
```

**Comment by 2003LK** [comment]
Oh yea I saw that as well and I assume it was how numpy deals with empty numbers. The visual output looked correct to me though, so I focused on that. Will the feedback numbers affect the models? It's similar to how there's an empty row for the guesses. I can get rid of both of them though.

**Review by jasozh — APPROVED** [review]

**Comment by jasozh** [comment]
The first line issue was fixed but I was still seeing a bunch of random numbers in self.feedback before the first guess was initialized. I fixed it by making the following changes:
```
self.guesses = np.array([])
self.feedback = np.array([])
```

and then changing `attempt_guess` to use `np.append` instead of `np.vstack`:
```
self.guesses = np.append(self.guesses, guesses_temp)
self.feedback = np.append(self.feedback, feedback_temp)
```

**Pull request merged**
